seed: 42
results_dir: results
max_new_tokens: 512
costs:
  base_gen_cost: 1.0
  large_inf_cost: 0.55
  large_gen_cost: 10.0
  expert_cost: 25.86 # Adjusted to fir system risk
  mistake_cost: 40.18 # Adjusted to fir system risk
base_model: meta-llama/Llama-3.2-1B-Instruct
large_model: meta-llama/Llama-3.1-8B-Instruct
batch_size: 105
max_input_length: 512
online:
  enable: true
  initial_uncertainty_threshold_base: 0.347
  initial_uncertainty_threshold_large: 0.347
  initial_M: 1.0
  lr_tau: 0.01
  lr_M: 0.005
  error_penalty: 10
sft:
  enable: false
  learning_rate: 0.0001
  buffer_size: 1
  lora_r: 32
  lora_alpha: 64
  lora_dropout: 0.1
verification_fn: surrogate_token_probs
uncertainty_fn: surrogate_token_uncertainties
uncertainty_samples: 5
precomputed:
  enable: true
  generation: true
  verification: true
  uncertainty: true
  path: /home/azureuser/caf83/helm/results/20250123/medmcqa/run_20250123_130018_medmcqa_models_1_8/results_medmcqa_models_1_8.csv
dataset:
  name: openlifescienceai/medmcqa
  subset: null
  split: validation
  num_samples: -1
device: cuda:0
name_postfix: experiment_3__medmcqa_1_8_rebuttal

