seed: 42
results_dir: results/medqa
max_new_tokens: 512 #Keep it small to start with
costs:
  base_gen_cost: 1.0
  large_inf_cost: 0.3
  large_gen_cost: 5.0
  expert_cost: 100.0
  mistake_cost: 250.0
#base_model: HuggingFaceTB/SmolLM-1.7B-Instruct
base_model: meta-llama/Llama-3.2-1B-Instruct
large_model: meta-llama/Llama-3.2-3B-Instruct
#large_model: /mnt/pdata/caf83/helm/me-llama/physionet.org/files/me-llama/1.0.0/MeLLaMA-13B-chat
batch_size: 7
max_input_length: 512
online:
  enable: false
  initial_uncertainty_threshold_base: 500
  initial_uncertainty_threshold_large: 500
  initial_M: 1.0
  lr_tau: 0.01
  lr_M: 0.01
  error_penalty: 10
sft:
  enable: false
  learning_rate: 1e-4
  buffer_size: 1
  lora_r: 32
  lora_alpha: 64
  lora_dropout: 0.1
verification_fn: surrogate_token_probs
uncertainty_fn: surrogate_token_uncertainties
uncertainty_samples: 1
precomputed:
  enable: true
  generation: true
  verification: true
  uncertainty: false
  path: "/home/azureuser/caf83/helm/results/20250121/medqa/run_20250121_152227_medqa_1_3/results_medqa_1_3.csv"
dataset:
  name: HuggingSara/medqa
  subset: 
  split: validation
  num_samples: -1
device: cuda:0
name_postfix: medqa_models_1_3