seed: 42
results_dir: "results"
max_new_tokens: 128
base_gen_cost: 1.0
large_inf_cost: 1.0
large_gen_cost: 25.0
expert_cost: 100.0
base_model: "meta-llama/Llama-3.2-1B-Instruct"
large_model: "meta-llama/Llama-3.1-8B-Instruct"
#large_model: "/mnt/pdata/caf83/helm/me-llama/physionet.org/files/me-llama/1.0.0/MeLLaMA-13B-chat"
probability_threshold: 1.0
uncertainty_threshold: 1.0
batch_size: 7
max_input_length: 512
num_samples: 21
verification_fn: "sequence_probability"
uncertainty_fn: "per_token_entropy"
response_prompt: "Please answer with only one of the multiple choice option in the brackets. The response should be in the format 'The best answer is: <ans>"
device: "cuda:0"
name_postfix: "sequence_probability"