experiment: first #"first" runs the deferal experiment, "second" runs the online deferral/abstention experiment
seed: 42
results_dir: results_neurips
max_new_tokens: 512
calibrate: true
calibration_size: 100
costs:
  output_input_price_ratio: 5
  abst_lambda: 0.1
  cost_lambda: 1e-5
base_model: Qwen/Qwen2.5-1.5B-Instruct
large_model: Qwen/Qwen2.5-3B-Instruct
batch_size: 7
max_input_length: 512
online:
  enable: false
  initial_xi_base: 0.05
  initial_xi_large: 0.05
  initial_phi_base: 0.5
  lr_tau: 0.05
  lr_M: 0.05
  error_penalty: 10
verification_fn: surrogate_token_probs
uncertainty_fn: surrogate_token_probs
uncertainty_samples: 1
precomputed:
  enable: false
  generation: false
  verification: false
  uncertainty: false
  path: 
dataset:
  name: AI-MO/aimo-validation-aime
  subset: null
  split: train
  num_samples: -1
device: cuda:1
name_postfix: debug



# dataset:
#   name: cais/mmlu
#   subset: all
#   split: validation
#   num_samples: -1

# dataset:
#   name: nlile/hendrycks-MATH-benchmark
#   subset: all
#   split: test
#   num_samples: -1

# dataset:
#   name: AI-MO/aimo-validation-aime
#   subset: null
#   split: train
#   num_samples: -1