seed: 42
results_dir: results
max_new_tokens: 512
base_gen_cost: 1.0
large_inf_cost: 0.3
large_gen_cost: 5.0
expert_cost: 100.0
base_model: meta-llama/Llama-3.2-3B-Instruct
large_model: meta-llama/Llama-3.1-8B-Instruct
batch_size: 7
max_input_length: 512
online:
  enable: false
  initial_uncertainty_threshold_base: 300
  initial_uncertainty_threshold_large: 300
  initial_M: 1
  lr_tau: 0.1
  lr_M: 0.005
  error_penalty: 10
sft:
  enable: false
  learning_rate: 0.0001
  buffer_size: 1
  lora_r: 32
  lora_alpha: 64
  lora_dropout: 0.1
verification_fn: surrogate_token_probs
uncertainty_fn: surrogate_token_uncertainties
uncertainty_samples: 5
precomputed:
  enable: true
  generation: true
  verification: true
  uncertainty: false
  path: "/home/azureuser/caf83/helm/results/run_20250123_000458_debug/results_debug.csv"
dataset:
  name: allenai/ai2_arc
  subset: ARC-Easy
  split: test
  num_samples: 21
device: cuda:1
name_postfix: debug