experiment: second
seed: 42
results_dir: results_neurips
max_new_tokens: 768
calibrate: true
calibration_size: 100
costs:
  output_input_price_ratio: 5
  abst_lambda: 0.1
  cost_lambda: 1e-5
base_model: meta-llama/Llama-3.2-1B-Instruct
large_model: meta-llama/Llama-3.1-8B-Instruct
batch_size: 100
max_input_length: 512
online:
  enable: true
  initial_xi_base: 0.05
  initial_xi_large: 0.05
  initial_phi_base: 0.5
  lr_tau: 0.05
  lr_M: 0.05
  error_penalty: 10
verification_fn: surrogate_token_probs
uncertainty_fn: surrogate_token_probs
uncertainty_samples: 1
precomputed:
  enable: true
  generation: true
  verification: true
  uncertainty: true
  path: /home/azureuser/caf83/cascaded-llms/neurips_save/run_20250730_200350_gen_mmlu_qwen_1_7/results_gen_mmlu_qwen_1_7_surrogate_token_probs_1_large.csv
dataset:
  name: cais/mmlu
  subset: all
  split: test
  num_samples: 1000 
device: cuda:0
name_postfix: qwen_mmlu_first
subject: 





# dataset:
#   name: cais/mmlu
#   subset: all
#   split: validation
#   num_samples: -1

# dataset:
#   name: nlile/hendrycks-MATH-benchmark
#   subset: null
#   split: test
#   num_samples: -1

# dataset:
#   name: AI-MO/aimo-validation-aime
#   subset: null
#   split: train
#   num_samples: -1