seed: 42
results_dir: results
max_new_tokens: 3 #Keep it small to start with
base_gen_cost: 1.0
large_inf_cost: 1.0
large_gen_cost: 25.0
expert_cost: 100.0
#base_model: HuggingFaceTB/SmolLM-1.7B-Instruct
base_model: meta-llama/Llama-3.2-3B-Instruct
large_model: meta-llama/Llama-3.1-8B-Instruct
#large_model: /mnt/pdata/caf83/helm/me-llama/physionet.org/files/me-llama/1.0.0/MeLLaMA-13B-chat
batch_size: 7
max_input_length: 512
online:
  enable: false
  initial_uncertainty_threshold_base: 2.0
  initial_uncertainty_threshold_large: 2.0
  initial_M: 1.0
  lr_tau: 0.01
  lr_M: 0.01
  error_penalty: 10
sft:
  enable: false
  learning_rate: 1e-4
  buffer_size: 1
  lora_r: 32
  lora_alpha: 64
  lora_dropout: 0.1
num_samples: 1000
verification_fn: surrogate_token_probs
uncertainty_fn: per_token_entropy
prompt_template: 'Please answer with only one of the multiple choice option in the brackets.'
dataset: medalpaca/medical_meadow_medqa
device: cuda:1
name_postfix: llama_3_8
